# Generated by Django 5.0 on 2023-12-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeacion.producto'),
        ),
        migrations.DeleteModel(
            name='Planeacion',
        ),
    ]
