# Generated by Django 5.0 on 2023-12-18 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0004_planeacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='planeacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeacion.planeacion'),
        ),
    ]
